#!/bin/bash

echo "筐・Ignore Permission Changes"
git config core.fileMode false

echo "筐・Set Correct Permissions"
chmod -R 777 storage

echo "筐・Install Composer Dependencies"
[[ -d vendor ]] || composer install

echo "筐・Install NPM Dependencies"
[[ -d node_modules ]] || npm install

echo "筐・Build Project Assets"
[[ -d assets/vendor ]] || npx gulp compile

echo "筐・Listen To Incoming Requests"
php-fpm
